### ISSUE TITLE
Good parameters return errors

### ISSUE THREAD

**Issue by maximejobin** [SatelliteWP/po-merger#1]
The following commands show errors:

    wp po merge fr-ca fr https://wordpress.org/plugins/disable-comments/ --diff-only --fuzzy=/app/packages/fr-ca.txt

    wp po merge fr-ca fr https://wordpress.org/plugins/simple-custom-css/ --fuzzy=/app/packages/fr-ca.txt

Message received:

    Error: The parameters have errors.

The reason is the environment used (development) is not supported as we use 'stable' by default. A parameter should be added to support this.

**Comment by PavelZaharciuc** [comment]
To fix the issue, two modifications were made:
1. The optional parameter "--env=<environment >" has been added. Thus, the user can now manually specify the environment.
2. If the process is on a plugin and the download has failed with the stable release, the package will try to download the developpement release.
