### ISSUE TITLE
Wrong stat number for "Copied from copy locale"

### ISSUE THREAD

**Issue by cedricus** [SatelliteWP/po-merger#14]
Stat number "Copied from copy locale" is incorrect because includes empty strings.
So when reading the results (ex Copied from copy locale: 102) you think to have many string to review but in fact sometimes 102 strings are empty...

Need to add a filter for empty strings in copy locale to avoid counting it.

Location to fix this issue: po_merger.php line from line 167 to 194

Quick fix adding simple test:
if(false === empty($copy_tr)) {
    $used_from_copy++;
} 

or maybe better for performance change the test to break the loop if the string is empty

if(true === empty($copy_tr)) {
    continue;
}

**Comment by maximejobin** [comment]
It seems like the code was doing its job correctly with line 167 but the GetText library changed and now returns null instead of false.

Good catch.

**Comment by maximejobin** [comment]
Fixed.
