### ISSUE TITLE
Generating empty file

### ISSUE THREAD

**Issue by maximejobin** [SatelliteWP/po-merger#3]
If WordPress, a theme or a plugin generated PO file should not contain anything because there is no translation to merge or validate, a message should be displayed like this:

    The query could not generate any strings to merge. Please check if the project is already fully translated.

**Comment by maximejobin** [comment]
As of now (there is no translation to do), the following command creates the problem:

    wp po merge fr-ca fr 4.3 --diff-only


It produces this file:

    # Translation of WordPress - 4.3.x in French (Canada)
    # This file is distributed under the same license as the WordPress - 4.3.x package.
    msgid ""
    msgstr ""
    "PO-Revision-Date: 2019-02-02 18:13:20+0000\n"
    "MIME-Version: 1.0\n"
    "Content-Type: text/plain; charset=UTF-8\n"
    "Content-Transfer-Encoding: 8bit\n"
    "Plural-Forms: nplurals=2; plural=n != 1;\n"
    "X-Generator: GlotPress/2.4.0-alpha\n"
    "Language: fr_CA\n"
    "Project-Id-Version: WordPress - 4.3.x\n"

It should produce no file and simply display a message.

**Comment by maximejobin** [comment]
@PavelZaharciuc 

I ran the command:

    wp po merge fr-ca fr 5.1 --diff-only

... and got the following result:

![image](https://user-images.githubusercontent.com/1080760/56587397-73eb6680-65af-11e9-8352-9988081a330d.png)

Here is the current status of that project:

![image](https://user-images.githubusercontent.com/1080760/56587532-b44ae480-65af-11e9-86db-8e7547e9f91f.png)

Shouldn't the "Administration" sub project return these 68 strings as they are not approved ?

**Comment by PavelZaharciuc** [comment]
The parameter "--diff-only" applies the filter "untranslated" to the download URL. Since the project doesn't have any untranslated strings, the request returns the PO file containing only the definition header. 
Thus, this behavior is normal.
